on:
  push:
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:

    - name: Check out the master branch
      uses: actions/checkout@v3

    - name: Print versions
      run: |
        echo ${{ runner.os }}
        echo ${{ runner.name }}
        uname -a
        cabal --version
        ghc --version

    - name: Build static executable
      run: cabal build all --enable-executable-static  --enable-split-sections
